### ISSUE TITLE
Manifest without symbolic name causes NPE

### ISSUE THREAD

**Issue by trancexpress** [iloveeclipse/plugindependencies#5]
Seen e.g. with the source jars for the following bundles:

http://jcenter.bintray.com/com/fasterxml/aalto-xml/1.0.0/

The exception stack is:

`Exception in thread "main" java.lang.NullPointerException
        at org.eclipselabs.plugindependencies.core.PluginParser.parsePluginPromXml(PluginParser.java:128)
        at org.eclipselabs.plugindependencies.core.PluginParser.createPluginAndAddToSet(PluginParser.java:107)
        at org.eclipselabs.plugindependencies.core.PluginParser.createPluginsAndAddToSet(PluginParser.java:84)
        at org.eclipselabs.plugindependencies.core.CommandLineInterpreter.readInEclipseFolder(CommandLineInterpreter.java:360)
        at org.eclipselabs.plugindependencies.core.Options$9.handle(Options.java:182)
        at org.eclipselabs.plugindependencies.core.CommandLineInterpreter.interpreteInput(CommandLineInterpreter.java:111)
        at org.eclipselabs.plugindependencies.core.MainClass.main(MainClass.java:18)`

If a bundle has a Manifest and the Manifest has no field `Bundle-SymbolicName`, `org.eclipselabs.plugindependencies.core.PluginParser.createPluginAndAddToSet(File, boolean)` will try to read the contents of the bundle's `plugin.xml`. If the bundle has no `plugin.xml`, the NPE is thrown.

`
        plugin = parseManifest(manifest, state);
        if (plugin == null) {
            if (manifest == null && pluginXml == null) {
                return RC_OK;
            }
            if(pluginXml == null){
                pluginXml = getPluginXml(pluginOrDirectory);
            }
            plugin = parsePluginPromXml(pluginXml);
            if (plugin == null) {
                return RC_OK;
            }
`

`parseManifest` returns `null`, but the `manifest` is not `null`. So `parsePluginPromXml` is reached and throws a NPE.

1. If the code needs `Bundle-SymbolicName`, it should throw an exception which indicates this.
2. If it doesn't need it, it should take care also of the case where no `plugin.xml` exists.

Having to browse the code to understand the NPE is not very optimal as far as error reporting goes.

**Comment by iloveeclipse** [comment]
Should be fixed already
